import ScreenModal from "../../ScreenModal";
import {QRCodeSVG} from "qrcode.react";
import {Formik} from "formik";
import Form from "../../../elements/Form";
import Field from "../../../elements/Field";
import validate from "../../../scripts/validate";
import {useEffect, useState} from "react";
import {useDispatch, useSelector} from "react-redux";
import {updateUser} from "../../../state/user";
import {closeModal} from "../../../state/app/modal";
import api from "@/scripts/api.js";
import auth from "@/scripts/auth.js";

const TwoStepLogin = () => {

    const user = useSelector(state => state.user.value)
    const [loading, setLoading] = useState({
        form: false,
        modal: true
    })
    const dispatch = useDispatch()
    const [twoStepData, setTwoStepData] = useState({})

    useEffect(() => {
        if (user.use_totp) {
            return console.log("Disable TOTP")
        }

        async function initialize() {
            await auth.authorizationToken('update_two_step_login')
                .then(async response => {
                    await api.get('user/security/two-step')
                        .then(response => {
                            setTwoStepData(response.data.data)
                            setLoading({
                                ...loading,
                                modal: false
                            })
                        })
                })
        }

        initialize()
    }, [])

    return (
        <ScreenModal id="two-step-login" heading="Two Step Login" subHeading="Secure your account with 2 Step Login"
                     loading={loading.modal}>
            <QRCodeSVG value={twoStepData.qrcode_data} bgColor="#ECF0F3" fgColor="#333344"/>
            <span id="totp-secret">{twoStepData.secret}</span>
            <div id="totp-text">
                <p>
                    Two Step Login, sometimes referred to as Two Factor Authentication (2FA), adds an extra layer of
                    security to your account by requiring a 6 digit code generated by a separate device to complete the
                    authentication process.
                    <br/><br/>
                    To enable Two Step Login, scan the QR code above using your <a target="_blank" rel="noreferrer"
                                                                                   href="https://www.google.com/search?q=best+authenticator+app&oq=best+authenticat&aqs=chrome.0.0i512j69i57j0i512l8.2828j0j1&sourceid=chrome&ie=UTF-8">authenticator
                    app</a> of choice and enter
                    the code displayed.
                </p>

            </div>
            <Formik initialValues={{
                code: ''
            }} onSubmit={(values) => {
                setLoading({
                    ...loading,
                    form: true
                })
                dispatch(updateUser({
                    ...user,
                    use_totp: true
                }))
                setTimeout(() => {
                    setLoading({
                        ...loading,
                        form: false
                    })
                    dispatch(closeModal())
                }, 500)
            }}>
                {({errors}) => (
                    <Form id="screen-modal-form" loading={loading.form}>
                        <Field name="code" placeholder="Code" validate={value => validate.require(value, 6, 6)}
                               error={errors.code ? 'Please enter a valid code' : ''}/>
                    </Form>
                )}
            </Formik>
        </ScreenModal>
    )
}

export default TwoStepLogin
